apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: pythonfastapidbpers
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pythonfastapidbpers
  template:
    metadata:
      labels:
        app: pythonfastapidbpers
    spec:
      containers:
      - name: pythonfastapidb
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.containerPort }}