apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: pythonfastapidbpers
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: {{ .Values.containerPort }}